### ISSUE TITLE
<center> text </center> 

### ISSUE THREAD

**Issue by alahmett** [alahmett/Learning#2]
I design the page as   ;
...<span style="color:#80BFFF">
          <center> 
     <h1>    {{ Hello World! }} </h1>   
   </center>
   <span style="color:#80BFFF">....
I found the blue color code  from http://html-color-codes.info/  and I text my words in it and then,
I think , by writing   <h1>  <h1>text</h1></h1>   I can determine the size of words in text.  At the begin, my aim was putting the text in the middle of screen,but the working logic of <center> text </center> is not as I aimed. So, now I am looking for another way to put  " {{ Hello World! }} " in the middle of screen. 

https://alahmett.github.io/Learning/

**Comment by AhmetCanSolak** [comment]
Currently it seems working. @alahmett  keep up good job! and dont forget to check the project I just opened. I will be updating the To Do column in that project.
