### ISSUE TITLE
Project#1:Since have a blue hello world text. Now lets have a photo under that text and put a 4x4 table under the photo.

### ISSUE THREAD

**Issue by alahmett** [alahmett/Learning#3]
I design my page by adding an image and a table. The image is about my favourite TV Series:the Sopranos. The table consists  information about cast of The Sopranos. I aimed to write title and contents with different color but I couldn't do that. They are all red now, but I am trying to find a way to write contents with black. Otherwise, I understand the concept of other codes, how to put a table and image.

**Comment by AhmetCanSolak** [comment]
Thank you for your work!
It is exactly what we want for this step.

Having different colors would be just cake after we start to work on classes and CSS deeper. For now just take it easy.

and as always please do not forget to check for the next assignment in project page.
